language: go
go:
- 1.9
install:
- sudo apt-get update -qq
- sudo apt-get install -qq xz-utils
- curl -LO https://github.com/upx/upx/releases/download/v3.94/upx-3.94-amd64_linux.tar.xz
- tar -xf upx-3.94-amd64_linux.tar.xz
- sudo mv upx-3.94-amd64_linux/upx /bin/
script:
- go build -ldflags "-w -s -extldflags '-static' -X main.versionString=$TRAVIS_TAG" -o go-init
- upx --brute go-init
deploy:
  provider: releases
  api_key:
    secure: aAh12GlGuVg5uVMzavbuKmYvQdeAo06dpP+tLJD+KKI/GPKANJ64WIwnBMrPuhLbdjOroiC+VWgydakjSPjnedKspB/Xg2oTTHTAN9soulYx8H3wCJSuu6vsEEjM67A1DCf06XoaTPHn0VPh1TuVCsdeXBsMulUz2jevuSU20G6KSRXsiVYplsnaXahJT0xjJl8g+4eM0x/toc8pgDfi3dhkrJay4gyY2cdFXEr3tLeCaiI6A0Xm4hRU8CPOKUiWqBV2PJO1l8VdTxHG4OtZho1xZ61S+bZZlXxmUOOTyUOJw8BxNZzywDh3KyhQ1C3i80kid5IWhjKrNtud0FYjAOhllooRD57h9IPhVyLNRSjhIrjQkl9CcJHhdrMOqFGuW6Qp7JzGwW53V/NrNaYNcnrcCiKwRmlMSxLFX+0sQHHc9wpCdDjns3hiH9rXFrahRoHzwUVLJRKwMsM0xNVmEYBx+/su5LDxL91o2l//JeLcxuEhwMLa7bbJJlEjfbP/e1yw4ejaPiBetwfRA5y6r/DtiCwMgQEXmtNEuQuIt+Byy19hINQv/R5Xz4EQe28ILj4STdVgWK/2oFFJLA8N/AHdWvhU6UuwkX41oP1Z0QjIROv9SRfYxV1tpR4r+cOXR09xEQm18Jci5UVEwq8r0r9tEzqrG0D4AV3OR3o/jJo=
  file: go-init
  skip_cleanup: true
  on:
    tags: true
